version: 2.1

jobs:
  build:
    docker:
      - image: cimg/python:3.8

    steps:
      - checkout

      - run:
          name: Install python versions
          command: |
            sudo apt-get update
            sudo apt-get install -y software-properties-common
            sudo add-apt-repository -y ppa:deadsnakes/ppa
            sudo apt-get update
            sudo apt-get install -y python3.9 python3.9-distutils python3.11 python3.12 pypy3

      - run:
          name: Install tox
          command: pip install tox

      - run:
          name: Run tox
          command: tox
